"""Maintain factual service and FAQ content, using the existing page shell."""
from pathlib import Path
import re, json, html

ROOT=Path(__file__).resolve().parent
BASE='https://askjconstruction.co.za/'
template=(ROOT/'service-areas-faq.html').read_text(encoding='utf-8')
schema=json.loads(re.search(r'<script type="application/ld\+json">(.*?)</script>',template,re.S)[1])
business=[x for x in schema['@graph'] if x['@type'] in ('GeneralContractor','WebSite')]
areas='Durban North, La Lucia, Umhlanga, Umdloti, Westbrook, Tongaat, Ballito, Shaka\'s Rock and Salt Rock'
contact='<p class="answer-contact"><a href="tel:+27837322142">+27 83 732 2142</a> / <a href="tel:+27785680809">+27 78 568 0809</a><br><a href="mailto:askjconstruction@gmail.com">askjconstruction@gmail.com</a></p><a class="answer-button" href="contact.html">Get A Free Quote</a>'
faqs=[
 ('Services',[
 ('What work does ASKJ Construction do?', 'We build homes and carry out <a href="home-renovations.html">renovations and additions</a>. We also offer <a href="frameless-showers.html">frameless showers and maintenance</a>, folding and sliding glass systems, Clearview fencing and project management. <a href="services.html">See all services</a>.'),
 ('Do you take on smaller jobs?', 'Yes. Our customer feedback covers bathroom renovations, repainting, shower servicing and glass-door replacement, alongside new home builds. Tell us what needs attention and where the property is.'),
 ('Can I see examples and customer feedback?', 'You can browse our <a href="projects.html">Projects page</a> and read <a href="customer-testimonials.html">customer testimonials</a>. For an enquiry, tell us which type of work you are considering so we can discuss the relevant experience.')]),
 ('Locations',[
 ('Which areas do you serve?', f'We serve Durban and the KwaZulu-Natal North Coast through Ballito and surrounding suburbs, including {areas}. Include your suburb when you contact us.'),
 ('Where are you based?', 'Our listed address is 103 Clarendon Road, Durban North, 4051. <a href="contact.html">Contact us</a> to arrange a consultation before visiting.')]),
 ('Preparing an enquiry',[
 ('What should I send for a quotation?', 'Start with your suburb, the work you want done and your contact details. Photographs help explain an existing space or a maintenance problem. If you have drawings, measurements or an intended start date, include those too.'),
 ('Can I enquire before I have drawings?', 'Yes. Describe your idea and what you have prepared so far. We can discuss the next step. The information needed for a detailed quotation depends on the work.'),
 ('How do I arrange a free consultation?', 'Use our <a href="contact.html">contact form</a>, call either number below or <a href="https://wa.me/27785680809">contact us on WhatsApp</a>. Give us your suburb and a brief description of the work to arrange the free in-home consultation offered on our contact page.')]),
 ('Project process',[
 ('What affects the cost of building or renovating?', 'The scope, site conditions, access, materials and finishes all affect the quotation. Work on an existing building may also depend on what is found on site. A description and photographs are useful starting points, but they do not replace an assessment.'),
 ('How long will the work take?', 'That depends on the scope, site access, approvals and material availability. Tell us about any date you need to work towards. Ask for a project-specific programme once the work has been assessed.'),
 ('Who handles drawings and approvals?', 'Our homebuilding process includes working with architects and, where applicable, estate design review teams. The responsibilities for drawings, submissions and approvals need to be agreed for your project. Share any existing plans or estate requirements when you enquire.'),
 ('Can I stay at home during a renovation?', 'It depends on the rooms affected, safe access and whether essential facilities remain available. Raise this early so it can be considered when the work is planned.'),
 ('What should I confirm before work starts?', 'Check the agreed scope, exclusions, finishes, programme and payment terms. Also ask how changes and any additional work will be recorded and priced.')])]

services=[
 dict(slug='luxury-home-builds',title='Luxury home builds',seo='Luxury Home Builders Durban & North Coast | ASKJ',desc='Discuss a new home build with ASKJ Construction in Durban and the KwaZulu-Natal North Coast. Explore the process and what to prepare for an enquiry.',image='b774e3d1b3849da11311.png',alt='Contemporary home exterior with timber cladding and a double garage',intro='A new home starts with decisions about the site, the way you want to live and what you want to spend. ASKJ Construction builds bespoke homes in Durban and the KwaZulu-Natal North Coast.',scope='We take enquiries for new residential builds and construction project management. Share the location, proposed size and current stage of your plans so we can discuss the work.',steps=[('Planning the build','Our published process starts with the design and planning stage, working with architects and estate design review teams where applicable. Bring any drawings, site information and estate requirements to the discussion.'),('Construction and coordination','Construction follows the agreed plans and scope. Discuss responsibilities, materials, site access and the programme before work starts.'),('Checks and handover','Quality checks and handover form part of our published process. Agree the project-specific inspections and handover requirements with the team.')],qa=[('What should I have ready for a new-build enquiry?','Send your suburb or estate, site details and any drawings you have. Include the approximate size of the home, preferred finishes and intended timing if you know them.'),('Can I discuss a build that is still at the planning stage?','Yes. Tell us what has been decided and what still needs work. Early discussions can help establish which information is needed before a detailed quotation.'),('Do you work with estate requirements?','Our published homebuilding process includes working with estate-approved architects and design review teams. Share the requirements for your estate so the project can be considered on that basis.')]),
 dict(slug='home-renovations',title='Home renovations and additions',seo='Home Renovations & Additions Durban | ASKJ',desc='Home renovation and addition enquiries in Durban, Umhlanga and the North Coast. Discuss your existing space, scope and next steps with ASKJ Construction.',image='a39782841d3d9dc4dbfa.png',alt='Kitchen interior with an island, timber cabinets and pendant lighting',intro='A renovation may involve updating a room, changing how a home works or adding more space. ASKJ Construction takes on home renovations and additions across Durban and the North Coast.',scope='Our services include home renovations and additions. Customer feedback also describes bathroom renovations, apartment repainting and smaller maintenance work. Explain which rooms or areas you want to change.',steps=[('Understand the existing space','Send photographs, measurements and any drawings. A site discussion helps establish the condition of the space, access and the work you have in mind.'),('Agree the scope','Discuss finishes, areas affected and whether anyone will remain in the property. Confirm the scope, exclusions and arrangements for changes before work begins.'),('Plan the work','The sequence and duration depend on the agreed work and the existing building. Raise access restrictions and any dates you need to work around during planning.')],qa=[('Do you handle bathroom renovations?','Yes. Bathroom renovations are among the work described by our customers. Share photographs and explain whether you want to change the layout, finishes, shower or other fittings.'),('Can you help with an addition rather than a full renovation?','Yes. Home additions are one of our listed services. Send any plans you have and explain what the new space will be used for.'),('Can you quote from photographs alone?','Photographs help us understand the enquiry. A detailed quotation may need measurements, drawings and a site assessment, depending on the work.')]),
 dict(slug='frameless-showers',title='Frameless showers and maintenance',seo='Frameless Showers & Repairs Durban | ASKJ',desc='Custom frameless shower installation, servicing and maintenance in Durban and the North Coast. Contact ASKJ about a new shower or an existing glass enclosure.',image='f2c40193cc8e0c45b8ed.png',alt='Frameless glass shower enclosure in a tiled bathroom',intro='ASKJ Construction offers custom frameless shower installation and maintenance in Durban and the North Coast. Contact us about a new enclosure or a problem with an existing shower.',scope='Our listed services cover frameless shower installation, servicing and maintenance. Customer feedback includes shower installations, servicing and the replacement of a broken glass door.',steps=[('Describe the enclosure','For a new shower, send photographs or plans of the bathroom and any available measurements. For maintenance, explain the problem and include photographs of the door, glass and fittings.'),('Assess what is needed','The next step depends on the opening, fittings and condition of the enclosure. Measurements and an assessment establish the work required.'),('Confirm the work','Discuss the proposed installation or repair, materials and timing before proceeding. Read our customer testimonials for feedback on shower work.')],qa=[('Do you service existing frameless showers?','Yes. Shower maintenance and servicing are listed services. Describe the fault and send photographs so we can discuss the next step.'),('Can I enquire about a broken shower door?','Yes. Our customer feedback includes glass-door replacement. Contact us with photographs and details of the enclosure so the required work can be assessed.'),('What information helps with a new shower enquiry?','Send your suburb, photographs or plans of the bathroom and any measurements you have. Explain whether this is a new installation or a replacement.')])]

def questions(items):
    return ''.join(f'<section class="answer-item"><h3>{html.escape(q)}</h3><p>{a}</p></section>' for q,a in items)

def write_page(slug,title,desc,body,extra=None):
    url=BASE+slug+'.html'
    s=re.sub(r'<title>.*?</title>',lambda _:f'<title>{html.escape(title)}</title>',template,flags=re.S)
    s=re.sub(r'<meta\b[^>]*(?:name="description"|property="og:(?:title|description|url)")[^>]*>','',s)
    s=re.sub(r'<link rel="canonical"[^>]*>',f'<link rel="canonical" href="{url}">',s)
    s=s.replace('</head>',f'<meta name="description" content="{html.escape(desc,quote=True)}"><meta property="og:title" content="{html.escape(title,quote=True)}"><meta property="og:description" content="{html.escape(desc,quote=True)}"><meta property="og:url" content="{url}"></head>')
    graph=business+[{'@type':'WebPage','@id':url+'#webpage','url':url,'name':title}]
    if extra:graph.extend(extra)
    s=re.sub(r'<script type="application/ld\+json">.*?</script>',lambda _:'<script type="application/ld+json">'+json.dumps({'@context':'https://schema.org','@graph':graph})+'</script>',s,flags=re.S)
    s=re.sub(r'<main\b.*?</main>',lambda _:'<main id="PAGES_CONTAINER" class="PAGES_CONTAINER" tabindex="-1" data-main-content="true">'+body+'<div class="local-search-link"><a href="service-areas-faq.html">Durban &amp; North Coast service areas and FAQs</a></div></main>',s,flags=re.S)
    (ROOT/(slug+'.html')).write_text(s,encoding='utf-8')

body='<article class="local-answers"><h1>Construction FAQs</h1><p class="answer-intro">Answers about building, renovations and shower services in Durban and the North Coast.</p>'
for group,items in faqs:body+=f'<h2 class="section-heading">{group}</h2>'+questions(items)
write_page('service-areas-faq','Construction FAQs Durban & North Coast | ASKJ','Find answers about ASKJ construction services, service areas, quotations, renovation planning and frameless showers in Durban and the North Coast.',body+contact+'</article>')
for d in services:
    slug=d['slug'];url=BASE+slug+'.html'
    body=f'<article class="local-answers service-detail"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="index.html">Home</a> / <a href="services.html">Services</a> / <span aria-current="page">{d["title"]}</span></nav><h1>{d["title"]}</h1><p class="answer-intro">{d["intro"]}</p><img class="service-photo" src="assets/{d["image"]}" width="1536" height="1024" alt="{d["alt"]}" loading="eager" fetchpriority="high"><h2 class="section-heading">Discuss your project</h2><p>{d["scope"]}</p>'
    for heading,text in d['steps']:body+=f'<section class="answer-item"><h2>{heading}</h2><p>{text}</p></section>'
    body+=f'<h2 class="section-heading">Where we work</h2><p>We serve Durban and the KwaZulu-Natal North Coast through Ballito and surrounding suburbs, including {areas}. <a href="service-areas-faq.html">Read our service area and enquiry FAQs</a>.</p><h2 class="section-heading">Questions about this service</h2>'+questions(d['qa'])
    body+='<p class="answer-contact"><a href="projects.html">Browse our Projects page</a> or <a href="customer-testimonials.html">read customer feedback</a>.</p>'+contact+'</article>'
    crumbs={'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':BASE},{'@type':'ListItem','position':2,'name':'Services','item':BASE+'services.html'},{'@type':'ListItem','position':3,'name':d['title'],'item':url}]}
    service={'@type':'Service','name':d['title'],'url':url,'provider':{'@id':BASE+'#business'},'areaServed':'Durban and the KwaZulu-Natal North Coast'}
    write_page(slug,d['seo'],d['desc'],body,[crumbs,service])
